#!/bin/bash

LANG=C

. ./function-common.sh

function install_rhel()
{
  local ret=0

  yum $DISABLE_EPEL install $PKG_install
  ret=$?

  return $ret
}

function setup_rhel()
{
  local ret=0

  mkdir -p $CONFD_agent
  if [ $(grep -c "^Include=${CONFD_agent}/*$" $CONF_agent) -eq 0 ]; then
    echo "Include=${CONFD_agent}/" >> $CONF_agent
  fi

  return $ret
}

function set_params()
{
  local ret=0

  eval $(grep ^Hostname= $CONF_agent | sed 's/\(.*=\)\(.*\)$/\1"\2"/')
  eval $(grep ^Server= $CONF_agent | sed 's/\(.*=\)\(.*\)$/\1"\2"/')
  eval $(grep ^ServerActive= $CONF_agent | sed 's/\(.*=\)\(.*\)$/\1"\2"/')

  read -p "Zabbix agent name [$Hostname] > " HOST_NAME
  read -p "Zabbix server address for passive check [$Server] > " SERVER
  read -p "Zabbix server address for active check [$ServerActive] > " SERVER_ACTIVE

cat << EOL >$CONF_append
# generated by install.sh; $(date +'at %T (%Z) on %B %d, %Y')
Hostname=${HOST_NAME:-$Hostname}
Server=${SERVER:-$Server}
ServerActive=${SERVER_ACTIVE:-$ServerActive}
AllowRoot=${ALLOW_ROOT}
EOL
  ret=$?

  return $ret
}

CONF_agent="/etc/zabbix/zabbix_agentd.conf"
CONFD_agent="/etc/zabbix/zabbix_agentd.d"
CONF_append="${CONFD_agent}/zabbix_agentd_append.conf"

PKG_core=" \
  zabbix-sender \
  zabbix-agent \
  "
PKG_install="$PKG_core"

install_${OS_DIST}             || exit 1
setup_${OS_DIST}               || exit 1
set_params                     || exit 1
enable_${OS_DIST} zabbix-agent || exit 1

exit 0

