#!/bin/bash

LANG=C

. ./function-common.sh

function install_rhel()
{
  local ret=0

  yum $DISABLE_EPEL install $PKG_install
  ret=$?

  return $ret
}

function setup_rhel()
{
  local ret=0

  mkdir -p $CONFD_server
  if [ $(grep -c "^Include=${CONFD_server}/*$" $CONF_server) -eq 0 ]; then
    echo "Include=${CONFD_server}/" >> $CONF_server
    ret=$?
  fi

  return $ret
}

function set_params()
{
  local ret=0

  eval $(grep ^ListenIP= $CONF_server | sed 's/\(.*=\)\(.*\)$/\1"\2"/')
  eval $(grep ^DBName= $CONF_server | sed 's/\(.*=\)\(.*\)$/\1"\2"/')
  eval $(grep ^DBUser= $CONF_server | sed 's/\(.*=\)\(.*\)$/\1"\2"/')
  eval $(grep ^DBPassword= $CONF_server | sed 's/\(.*=\)\(.*\)$/\1"\2"/')
  eval $(grep ^DBHost= $CONF_server | sed 's/\(.*=\)\(.*\)$/\1"\2"/')
  DBHost=${DBHost:-localhost}
  ListenIP=${ListenIP:-0.0.0.0}

  read -p "Zabbix server listen ip address [$ListenIP] > " LISTEN_IP
  read -p "Zabbix server database name [$DBName] > " DB_NAME
  read -p "Zabbix server database user [$DBUser] > " DB_USER
  read -p "Zabbix server database password [$DBPassword] > " DB_PASSWORD
  read -p "Zabbix server database host [$DBHost] > " DB_HOST

cat << EOL >$CONF_append
# generated by install.sh; $(date +'at %T (%Z) on %B %d, %Y')
ListenIP=${LISTEN_IP:-$ListenIP}
DBName=${DB_NAME:-$DBName}
DBUser=${DB_USER:-$DBUser}
DBPassword=${DB_PASSWORD:-$DBPassword}
DBHost=${DB_HOST:-$DBHost}
EOL
  ret=$?

  if [ $USE_JMX -eq 1 ]; then
    read -p "Zabbix Java Gateway ip address > " JMX_IP
    cat << EOL >>$CONF_append
JavaGateway=${JMX_IP:-127.0.0.1}
EOL
    ret=$((ret+$?))
  fi

  return $ret
}

function setup_web()
{
  local ret=0

  setup_timezone
  setup_webconf

  return $ret
}

function setup_timezone()
{
  local ret=0

  read -e -p "Set your timezone [Asia/Tokyo] > " TIME_ZONE
  TIME_ZONE="${TIME_ZONE:-Asia/Tokyo}"

  edit_tz_${OS_DIST}
  ret=$?

  return $ret
}

function edit_tz_rhel()
{
  local ret=0
  local conf_file="/etc/httpd/conf.d/zabbix.conf"
  local tmpl_file=""
  local httpd_ver=""

  if [ ! -e $conf_file ]; then
    httpd_ver=$(rpm -q --qf "%{V}" httpd)
    tmpl_file="$(rpm -ql zabbix-web | grep "httpd2${httpd_ver:3:1}-example.conf")"

    if [ -f $tmpl_file ]; then
      cp $tmpl_file $conf_file
    fi
  fi

  sed -i 's|^\(\s*#\s*\)\(php_value\sdate\.timezone\) .*|\t\2 '${TIME_ZONE}'|' \
    $conf_file
  ret=$?

  return $ret
}

function setup_webconf()
{
  local ret=0

  return $ret
}

CONF_server="/etc/zabbix/zabbix_server.conf"
CONFD_server="/etc/zabbix/zabbix_server.d"
CONF_append="${CONFD_server}/zabbix_server_append.conf"

PKG_core=" \
  zabbix-sender \
  zabbix-get \
  zabbix-web \
  zabbix-web-japanese \
  "
PKG_mysql=" \
  zabbix-server-mysql \
  zabbix-web-mysql \
  "
PKG_pgsql=" \
  zabbix-server-pgsql \
  zabbix-web-pgsql \
  "
PKG_java=" \
  zabbix-java-gateway \
  "

PKG_install="$PKG_core"
if [ $USE_PGSQL -eq 1 ]; then
  PKG_install+=" $PKG_pgsql"
else
  PKG_install+=" $PKG_mysql"
fi

if [ $USE_JMX -eq 1 ]; then
  PKG_install+=" $PKG_java"
fi

install_${OS_DIST}              || exit 1
setup_${OS_DIST}                || exit 1
set_params                      || exit 1
setup_web                       || exit 1
enable_${OS_DIST} zabbix-server || exit 1

if [ $WITH_AGENT -eq 1 ]; then
  ./install-agent.sh || exit 1
fi

exit 0

