#!/bin/bash

LANG=C

. ./function-common.sh

function install_rhel()
{
  yum $DISABLE_EPEL install $PKG_install
}

function setup_rhel()
{
  mkdir -p $CONFD_proxy

  if [ $(grep -c "^Include=${CONFD_proxy}/*$" $CONF_proxy) -eq 0 ]; then
    echo "Include=${CONFD_proxy}/" >> $CONF_proxy
  fi
}

function set_params()
{
  local ret=0

  eval $(grep ^Server= $CONF_proxy | sed 's/\(.*=\)\(.*\)$/\1"\2"/')
  eval $(grep ^ListenIP= $CONF_proxy | sed 's/\(.*=\)\(.*\)$/\1"\2"/')
  eval $(grep ^DBName= $CONF_proxy | sed 's/\(.*=\)\(.*\)$/\1"\2"/')
  eval $(grep ^DBUser= $CONF_proxy | sed 's/\(.*=\)\(.*\)$/\1"\2"/')
  eval $(grep ^DBPassword= $CONF_proxy | sed 's/\(.*=\)\(.*\)$/\1"\2"/')
  eval $(grep ^DBHost= $CONF_proxy | sed 's/\(.*=\)\(.*\)$/\1"\2"/')
  DBHost=${DBHost:-localhost}

  read -p "Zabbix server ip address [$Server] > " SERVER
  read -p "Zabbix proxy hostname [$Hostname] > " HOST_NAME
  read -p "Zabbix proxy listen ip address [$ListenIP] > " LISTEN_IP
  read -p "Zabbix proxy database name [$DBName] > " DB_NAME
  read -p "Zabbix proxy database user [$DBUser] > " DB_USER
  read -p "Zabbix proxy database password [$DBPassword] > " DB_PASSWORD
  read -p "Zabbix proxy database host [$DBHost] > " DB_HOST

cat << EOL >$CONF_append
# generated by install.sh; $(date +'at %T (%Z) on %B %d, %Y')
ProxyMode=${PROXY_MODE}
Server=${SERVER:-$Server}
ListenIP=${LISTEN_IP:-$ListenIP}
Hostname=${HOST_NAME:-$Hostname}
DBName=${DB_NAME:-$DBName}
DBUser=${DB_USER:-$DBUser}
DBPassword=${DB_PASSWORD:-$DBPassword}
DBHost=${DB_HOST:-$DBHost}
AllowRoot=${ALLOW_ROOT}
EOL
  ret=$?

  if [ $USE_JMX -eq 1 ]; then
    read -p "Zabbix Java Gateway IP address [127.0.0.1] > " JMX_IP

    cat << EOL >>$CONF_append
JavaGateway=${JMX_IP:-127.0.0.1}
EOL
    ret=$((ret+$?))
  fi

  return $ret
}

CONF_proxy="/etc/zabbix/zabbix_proxy.conf"
CONFD_proxy="/etc/zabbix/zabbix_proxy.d"
CONF_append="${CONFD_proxy}/zabbix_proxy_append.conf"

PKG_core=" \
  zabbix-sender \
  zabbix-get \
  zabbix-proxy \
  "
PKG_mysql=" \
  zabbix-proxy-mysql \
  "
PKG_pgsql=" \
  zabbix-proxy-pgsql \
  "
PKG_java=" \
  zabbix-java-gateway \
  "

PKG_install="$PKG_core"
if [ $USE_PGSQL -eq 1 ]; then
  PKG_install+=" $PKG_pgsql"
else
  PKG_install+=" $PKG_mysql"
fi

if [ $USE_JMX -eq 1 ]; then
  PKG_install+=" $PKG_java"
fi

install_${OS_DIST}             || exit 1
setup_${OS_DIST}               || exit 1
set_params                     || exit 1
enable_${OS_DIST} zabbix-proxy || exit 1

if [ $WITH_AGENT -eq 1 ]; then
  ./install-agent.sh || exit 1
fi

exit 0

